// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('angularToolkitApp').controller('MainCtrl', function($scope, $rootScope, $window) {
    $scope.photoFrame = 'images/sample-frame.png';
    $scope.init = function() {
      $window.document.title = 'AngularJS Toolkit';
      console.log('ONLINE: ' + $rootScope.online);
      return $scope.cameraActive = true;
    };
    $scope.publish = function() {
      return console.log('Publishing media');
    };
    $scope.onDisconnect = function() {
      return console.log('Disconnect event');
    };
    $scope.onConnect = function() {
      return console.log('Connect Event');
    };
    return $scope.init();
  });

}).call(this);
