// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('angularToolkitApp').controller('MainCtrl', function($scope, $rootScope, $document) {
    $scope.init = function() {
      $document.title = 'AngularJS Toolkit';
      return console.log('ONLINE: ' + $rootScope.online);
    };
    $scope.publish = function() {
      return console.log('Publishing media');
    };
    $scope.onDisconnect = function() {
      return console.log('Disconnect event');
    };
    $scope.onConnect = function() {
      return console.log('Connect Event');
    };
    return $scope.init();
  });

}).call(this);
